//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlodaStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCategory
    {
        public AccountCategory()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public string AccountCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Avatar { get; set; }
        public string Thumb { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
