//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlodaStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Articles = new HashSet<Article>();
            this.ArticleCategories = new HashSet<ArticleCategory>();
            this.ArticleMainCategories = new HashSet<ArticleMainCategory>();
            this.ClientCategories = new HashSet<ClientCategory>();
            this.ContactCategories = new HashSet<ContactCategory>();
            this.Products = new HashSet<Product>();
            this.ProductCategories = new HashSet<ProductCategory>();
            this.ProductMainCategories = new HashSet<ProductMainCategory>();
        }
    
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Avatar { get; set; }
        public string Thumb { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Mobi { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string AccountCategoryID { get; set; }
    
        public virtual AccountCategory AccountCategory { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
        public virtual ICollection<ArticleMainCategory> ArticleMainCategories { get; set; }
        public virtual ICollection<ClientCategory> ClientCategories { get; set; }
        public virtual ICollection<ContactCategory> ContactCategories { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ICollection<ProductMainCategory> ProductMainCategories { get; set; }
    }
}
